### PR TITLE
Update ipset-US-hosting.lst

### PR DESCRIPTION
**Pull request by rsherstobitoff1980**
Research foundation

### CODE REVIEW

**Comment by rsherstobitoff1980** [comment]
Research foundation IPs

**Comment by rsherstobitoff1980** [comment]
Research IPs

**Comment by DPsystems** [comment]
There is insufficient evidence the IP in question is worthy of being excluded from our list.  More specific evidence on the nature of those operating on this IP block is needed.   Who is sponsoring the research?  For what purpose?

**Comment by DPsystems** [comment]
For any future requests, please provide more details.   Thanks.  Your change also appears to be  from an older branch.

**Pull request closed without merging**
