### PR TITLE
Update set-iptables.sh-config

### PR DESCRIPTION
**Pull request by ychaouche**
4190 is for manage sieve (sieve filters)

### CODE REVIEW

**Comment by DPsystems** [comment]
need more explanation when requests like this are made

**Comment by ychaouche** [comment]
They are made anytime a user wants to edit server-side mail filters using the ManageSieve Protocol.

**Comment by ychaouche** [comment]
oops, 
apparently I misunderstood the question.
The documentation in the file I changed mentions that port 4190 is for Plesk Dovecot,
when in reality it is for the ManageSieve protocol.

**Comment by DPsystems** [comment]
Ok, thank you - I will make that note.

**Pull request closed without merging**
